# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.17.3]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm install

    - name: Run the tests
      run: npm run test

    - name: Build
      run: npm run build
    
    - name: Configure SSH key
      uses: webfactory/ssh-agent@v0.4.1
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: test
      run: |
        cat $HOME/.ssh/id_rsa
        pwd
        cd 
        ls -al
        cd .ssh
        pwd
        ls -al
        cat private
    - name: Deploy
      env:
        SERVER_IP: ${{secrets.SERVER_IP}}
        USER: ${{secrets.USER}}
        FRONT_PROJECT_PATH: ${{secrets.FRONT_PROJECT_PATH}}
      run: |
        scp -o StrictHostKeyChecking=no -r build/* ubuntu@100.25.164.107:/home/ubuntu
        rsync -avz -e "ssh -o StrictHostKeyChecking=no" build/* ubuntu@100.25.164.107:/home/ubuntu


      
    
   